name: FloodgatePrefixGuard
version: 1.3.2
main: me.muzone.floodgateprefixguard.FloodgatePrefixGuard
api-version: 1.20
author: MZQ
depend: [floodgate]
description: Protects Bedrock players from UUID desync.

commands:
  floodgateprefixguard:
    description: Main command for FPG
    aliases: [fpg]
    usage: /fpg reload
    permission: fpg.admin

permissions:
  fpg.admin:
    description: Allows reloading the config
    default: op
  fpg.notify:
    description: Receives notification when a player is kicked by FPG
    default: op