name: FloodgatePrefixGuard
version: 1.1.0
main: me.muzone.floodgateprefixguard.FloodgatePrefixGuard
api-version: 1.20
author: Muzone
depend: [floodgate]
description: Protects Bedrock players from UUID desync.

commands:
  floodgateprefixguard:
    description: Main command for FPG
    aliases: [fpg]
    usage: /fpg reload
    permission: fpg.admin

permissions:
  fpg.admin:
    description: Allows reloading the config
    default: op